name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit and tag
        id: vars
        run: |
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build & Push Caddy
        uses: docker/build-push-action@v6
        with:
          context: .
          file:  ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/sport-app:latest
            ghcr.io/${{ github.repository_owner }}/sport-app:${{ steps.vars.outputs.tag }}
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}

      - name: Build & Push PHP fpm
        uses: docker/build-push-action@v6
        with:
          context: .
          file:  ./docker/production/php/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/sport-php:latest
            ghcr.io/${{ github.repository_owner }}/sport-php:${{ steps.vars.outputs.tag }}
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}

      - name: Notify Telegram
        if: success()
        env:
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        run: |
          MESSAGE=$(cat << 'EOF'
          âœ… *Docker Ð¾Ð±Ñ€Ð°Ð·Ñ‹ ÑÐ¾Ð±Ñ€Ð°Ð½Ñ‹ Ð¸ Ð¾Ð¿ÑƒÐ±Ð»Ð¸ÐºÐ¾Ð²Ð°Ð½Ñ‹, ÐÐÐ”Ðž Ð”Ð•ÐŸÐ›ÐžÐ˜Ð¢Ð¬!*

          ðŸ‘¤ ÐÐ²Ñ‚Ð¾Ñ€ Ð¿ÑƒÑˆÐ°: `${{ github.actor }}`
          ðŸ’¬ ÐšÐ¾Ð¼Ð¼ÐµÐ½Ñ‚Ð°Ñ€Ð¸Ð¹ Ðº Ð¿ÑƒÑˆÑƒ:
          `${{ github.event.head_commit.message }}`

          ðŸ“¦ ÐžÐ±Ñ€Ð°Ð·Ñ‹:
          - `ghcr.io/${{ github.repository_owner }}/sport-app:latest`
          - `ghcr.io/${{ github.repository_owner }}/sport-app:${{ steps.vars.outputs.tag }}`

          ðŸ’¾ ÐšÐ¾Ð¼Ð¼Ð¸Ñ‚: `${{ steps.vars.outputs.commit }}`
          ðŸ·ï¸ Ð¢ÐµÐ³: `${{ steps.vars.outputs.tag }}`
          EOF
          )

          curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg chat_id "$TG_CHAT_ID" \
              --arg text "$MESSAGE" \
              --arg mode "Markdown" \
              '{chat_id: $chat_id, text: $text, parse_mode: $mode}')"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"${{ secrets.TG_CHAT_ID }}"'",
              "parse_mode": "Markdown",
              "text": "âŒ *ÐžÑˆÐ¸Ð±ÐºÐ° Ð² GitHub Actions Workflow!*\n\nðŸ§‘ ÐÐ²Ñ‚Ð¾Ñ€: ${{ github.actor }}\nðŸ“ Commit: `${{ github.sha }}`",
              "reply_markup": {
                "inline_keyboard": [[
                  {
                    "text": "ðŸ“„ ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ Ð»Ð¾Ð³",
                    "url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
                  }
                ]]
              }
            }'